import Head from 'next/head'
import { useRouter } from 'next/router'
import useSWR from 'swr'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import { AppBar, Toolbar, IconButton, CircularProgress, Button, Chip } from '@mui/material'
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft'
import Project from '../../components/Projects/Project'

const inter = Inter({ subsets: ['latin'] })

const fetcher = (url) => fetch(url).then((res) => res.json())

export default () => {
  const { query } = useRouter()
  const { data, error } = useSWR(`/api/projects/${query.id}`, fetcher)

  if (error) return (
    <div className={styles.page}>
      Failed to Load
    </div>
  )

  if (!data) return (
    <div className={styles.page}>
      <CircularProgress />
    </div>
  )

  return (
    <>
      <Head>
        <title>Julie Evans Portfolio - {data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div 
        className={styles.main}
        // className={styles.page}
        // style={{
        //   display: "flex",
        //   flexDirection: "column",
        //   minHeight: "100vh",
        //   padding: "4rem"
        // }}
      >
        <AppBar 
          color="transparent" 
          className={styles.header} 
        >
          <Toolbar variant="dense">
            <IconButton color="primary" component="a" href="/">
              <ChevronLeftIcon />
            </IconButton>
          </Toolbar>
        </AppBar>

        <Project data={data} />
      </div>
    </>
  )
}