import Head from 'next/head'
import { useRouter } from 'next/router'
import useSWR from 'swr'
import styles from '../../styles/Home.module.css'
import { AppBar, Toolbar, IconButton, CircularProgress } from '@mui/material'
import ChevronLeftIcon from '@mui/icons-material/ChevronLeft'
import Project from '../../components/Projects/Project'

const fetcher = (url) => fetch(url).then((res) => res.json())

export default () => {
  const { query } = useRouter()
  const { data, error } = useSWR(`/api/projects/${query.id}`, fetcher)

  if (error) return (
    <div 
      className={styles.main} 
      style={{ justifyContent: "center", height: "calc(100vh - 8rem)" }}
    >
      <h1>Failed to Load</h1>
    </div>
  )

  if (!data) return (
    <div 
      className={styles.main} 
      style={{ justifyContent: "center", height: "calc(100vh - 8rem)" }}
    >
      <CircularProgress size={60} />
    </div>
  )

  return (
    <>
      <Head>
        <title>Julie Evans Portfolio - {data.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo-100.png" />
      </Head>
      
      <div className={styles.main}>
        <AppBar 
          color="transparent" 
          className={styles.header} 
        >
          <Toolbar variant="dense">
            <IconButton color="primary" component="a" href="/">
              <ChevronLeftIcon />
            </IconButton>
          </Toolbar>
        </AppBar>

        <Project data={data} />
      </div>
    </>
  )
}